context:
  version: "0.1.7"

package:
  name: nanorecall
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/n/nanorecall/nanorecall-${{ version }}.tar.gz
  sha256: d564dc58fd99c5a143be6f57937dab901f1f99717cb779eaaa79e3001b5e202f

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=61.0.0
    - wheel
  run:
    - python >=${{ python_min }}
    - numpy >=1.20

tests:
  - python:
      python_version:
        - ${{ python_min }}.*
        - "*"
      imports:
        - nanorecall
      pip_check: false
  - script:
      - python -m nanorecall.cli --help

about:
  homepage: https://github.com/eminsk/nanorecall
  summary: 100% Private, Zero-Cloud, Bare-Metal Desktop Memory & Screen Search Engine
  description: |
    A high-performance, open-source, 100% private alternative to Microsoft
    Windows Recall engineered with pure C99/SIMD and zero cloud telemetry.
  license: MIT
  license_file: LICENSE
  repository: https://github.com/eminsk/nanorecall
  documentation: https://github.com/eminsk/nanorecall#readme

extra:
  recipe-maintainers:
    - eminsk
